---
# make sure to install
# ansible-galaxy collection install community.docker
- name: Install Docker and Portainer Agent
  hosts: all
  become: true
  tasks:
    - name: Install required system packages
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - python3-docker
        state: present
        update_cache: true

    - name: Download Docker install script
      ansible.builtin.get_url:
        url: https://get.docker.com
        dest: /tmp/get-docker.sh
        mode: '0755'

    - name: Execute Docker install script
      ansible.builtin.command:
        cmd: /tmp/get-docker.sh
        creates: /usr/bin/docker

    - name: Remove Docker install script
      ansible.builtin.file:
        path: /tmp/get-docker.sh
        state: absent

    - name: Ensure Docker service is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Add ansible user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true
      when: ansible_user != "root"

    - name: Create Portainer Agent volume
      community.docker.docker_volume:
        name: portainer_agent_data
        state: present

    - name: Start Portainer Agent container
      community.docker.docker_container:
        name: portainer_agent
        image: portainer/agent:latest
        state: started
        restart_policy: always
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /var/lib/docker/volumes:/var/lib/docker/volumes
          - portainer_agent_data:/data
        ports:
          - "9001:9001"
